// <copyright file="GrowableIndustrialAI.cs" company="algernon (K. Algernon A. Sheppard)">
// Copyright (c) algernon (K. Algernon A. Sheppard). All rights reserved.
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
// </copyright>

namespace PloppableRICO
{
    using ColossalFramework.Math;
    using static WorkplaceAIHelper;

    /// <summary>
    /// Replacement for Industrial AI for growable RICO buildings.
    /// </summary>
    public class GrowableIndustrialAI : IndustrialBuildingAI, IWorkplaceLevelCalculator
    {
        /// <summary>
        /// RICO data record.
        /// </summary>
        public RICOBuilding m_ricoData;

        /// <summary>
        /// Construction cost of this building.  Ignored for growables - having it here saves having extra checks in ConvertPrefabs().
        /// Sets a reasonable default, but will be overwritten by ConvertPrefabs() for ploppables.
        /// </summary>
        public int m_constructionCost = 10;

        /// <summary>
        /// Number of workplaces in this building.
        /// Sets a reasonable default, but will be overwritten by ConvertPrefabs().
        /// </summary>
        public int m_workplaceCount = 1;

        /// <summary>
        /// Indicates whether or not pollution is enabled for this building.
        /// Can be overwritten by ConvertPrefabs().
        /// </summary>
        public bool m_pollutionEnabled = true;

        /// <summary>
        /// Calculates the workplaces for this building according to RICO settings.
        /// </summary>
        /// <param name="level">Building level</param>
        /// <param name="r">Randomizer</param>
        /// <param name="width">Building plot width (in cells).</param>
        /// <param name="length">Building plot length (in cells).</param>
        /// <param name="level0">The number of uneducated jobs.</param>
        /// <param name="level1">The number of educated jobs.</param>
        /// <param name="level2">The number of well-educated jobs.</param>
        /// <param name="level3">The number of highly-educated jobs.</param>
        public override void CalculateWorkplaceCount(ItemClass.Level level, Randomizer r, int width, int length, out int level0, out int level1, out int level2, out int level3) =>
            WorkplaceAIHelper.CalculateWorkplaceCount(level, m_ricoData, this, r, width, length, out level0, out level1, out level2, out level3);

        /// <summary>
        /// Calculates the workplaces for this building according to base method (non-RICO settings).
        /// Called by WorkPlaceAIHelper to access the base game method; for implementing functionality of mods that have detoured/patched that method (e.g. Realistic Population mods).
        /// </summary>
        /// <param name="level">Building level.</param>
        /// <param name="r">Randomizer.</param>
        /// <param name="width">Building plot width (in cells).</param>
        /// <param name="length">Building plot length (in cells).</param>
        /// <param name="level0">The number of uneducated jobs.</param>
        /// <param name="level1">The number of educated jobs.</param>
        /// <param name="level2">The number of well-educated jobs.</param>
        /// <param name="level3">The number of highly-educated jobs.</param>
        public void CalculateBaseWorkplaceCount(ItemClass.Level level, Randomizer r, int width, int length, out int level0, out int level1, out int level2, out int level3)
        {
            base.CalculateWorkplaceCount(level, r, width, length, out level0, out level1, out level2, out level3); ;
        }

        /// <summary>
        /// Returns the pollution generated by this building.
        /// </summary>
        /// <param name="level">Building level.</param>
        /// <param name="productionRate">Bulding production rate.</param>
        /// <param name="cityPlanningPolicies">Any applicable policies.</param>
        /// <param name="groundPollution">Ground pollution generated by this building.</param>
        /// <param name="noisePollution">Noise pollution generated by this builidng.</param>
        public override void GetPollutionRates(ItemClass.Level level, int productionRate, DistrictPolicies.CityPlanning cityPlanningPolicies, out int groundPollution, out int noisePollution)
        {
            // If pollution is disabled, return zero.
            if (!m_pollutionEnabled)
            {
                groundPollution = 0;
                noisePollution = 0;
                return;
            }

            // Otherwise, use base method to calculate normal pollution levels.
            base.GetPollutionRates(level, productionRate, cityPlanningPolicies, out groundPollution, out noisePollution);
        }

        /// <summary>
        /// Check to see if this building is unlocked (by progression level or other prerequisites).
        /// RICO buildings are always unlocked.
        /// </summary>
        /// <returns>Whether the building is currently unlocked (always true).</returns>
        public override bool CheckUnlocking()
        {
            return true;
        }
    }
}